<?php

/**
 * Default purchi layout (tenant 1 legacy mapping).
 * Copy to organization.purchi_config JSON or override per tenant.
 * Revert dynamic mode: organization.purchi_use_dynamic = 0
 */
return [

    'version' => 1,

    'excluded_vendor_ids' => [
        7, 8, 9, 17, 18, 289, 290, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
        33, 34, 36, 135, 138, 346, 278, 285, 294, 298, 264, 288, 306, 311, 312,
        315, 323, 340, 343, 366, 374, 377, 379, 387, 394, 413, 429, 437, 341, 472,
    ],

    'vendor_cr_exclude_ids' => [7, 311, 285, 288, 429, 437, 33],

    'customer_receive_slugs' => [
        'fazul_qadir_receive', 'shafiq_karyana_receive', 'abdul_ghaffar_ghar_receive',
        'ammar_abdullah_ghar_receive', 'imdad_khata_receive', 'imran_niazi_receive',
        'sir_murtaza_sahib_receive', 'master_khalid_faroq_shah_receive',
    ],

    'customer_banam_slugs' => [
        'fazul_qadir_banam', 'shafiq_karyana_banam', 'abdul_ghaffar_ghar_banam',
        'ammar_abdullah_ghar_banam', 'imdad_khata_banam', 'imran_niazi_banam',
        'sir_murtaza_sahib_banam', 'master_khalid_faroq_shah_banam',
    ],

    'pools' => [
        'mutafirq_udhar_receive' => [
            'label' => 'متفرق ادھار',
            'side' => 'incoming',
            'sort' => 15,
            'direction' => 'cr',
            'exclude_customer_ids' => [5, 8, 49, 97, 105, 107, 113, 115, 126, 145, 157, 170, 48, 242],
        ],
        'mutafariq_udhar_banam' => [
            'label' => 'متفرق ادھار',
            'side' => 'outgoing',
            'sort' => 10,
            'direction' => 'dr',
            'exclude_customer_ids' => [5, 8, 49, 97, 114, 115, 356, 107, 113, 126, 145, 157, 170, 48, 242, 413],
        ],
    ],

    'special' => [
        'openning_balance' => [
            'label' => 'نقد دکان',
            'side' => 'incoming',
            'sort' => 5,
            'type' => 'customer_ledger',
            'customer_id' => 170,
            'direction' => 'cr',
            'trx_type' => 3,
        ],
        'expense' => [
            'label' => 'دکان خرچہ',
            'side' => 'outgoing',
            'sort' => 200,
            'type' => 'customer_ledger',
            'customer_id' => 5,
            'direction' => 'dr',
            'trx_type' => 3,
        ],
        'ilyas_bakhtawar' => [
            'label' => 'الیاس بختاور',
            'side' => 'incoming',
            'sort' => 25,
            'type' => 'customer_ledger',
            'customer_id' => 105,
            'direction' => 'cr',
        ],
        'open_khad' => [
            'label' => 'open_khad',
            'side' => 'internal',
            'type' => 'customer_ledger',
            'customer_id' => 356,
            'direction' => 'dr',
        ],
        'beej_khareed' => [
            'label' => 'بیج',
            'side' => 'outgoing',
            'sort' => 180,
            'type' => 'vendor_ledger',
            'vendor_id' => 28,
            'direction' => 'dr',
            'trx_type' => 3,
        ],
        'mcb_ka' => [
            'label' => 'MCB کوٹ ادو',
            'side' => 'outgoing',
            'sort' => 170,
            'type' => 'vendor_ledger',
            'vendor_id' => 288,
            'direction' => 'dr',
        ],
        'mcb_ka_jama' => [
            'label' => 'MCB کوٹ ادو',
            'side' => 'incoming',
            'sort' => 80,
            'type' => 'vendor_ledger',
            'vendor_id' => 288,
            'direction' => 'cr',
        ],
        'meezan_bank_banam' => [
            'label' => 'میزان بینک عبدالشکور',
            'side' => 'outgoing',
            'sort' => 175,
            'type' => 'vendor_ledger',
            'vendor_id' => 429,
            'direction' => 'dr',
        ],
        'meezan_bank_jama' => [
            'label' => 'میزان بینک عبدالشکور',
            'side' => 'incoming',
            'sort' => 85,
            'type' => 'vendor_ledger',
            'vendor_id' => 429,
            'direction' => 'cr',
        ],
        'ubl_aftab_banam' => [
            'label' => 'UBL آفتاب',
            'side' => 'outgoing',
            'sort' => 176,
            'type' => 'vendor_ledger',
            'vendor_id' => 437,
            'direction' => 'dr',
        ],
        'ubl_aftab_jama' => [
            'label' => 'UBL آفتاب',
            'side' => 'incoming',
            'sort' => 90,
            'type' => 'vendor_ledger',
            'vendor_id' => 437,
            'direction' => 'cr',
        ],
        'hbl_m_waqas_jama' => [
            'label' => 'HBL وقاص',
            'side' => 'incoming',
            'sort' => 75,
            'type' => 'vendor_ledger',
            'vendor_id' => 311,
            'direction' => 'cr',
            'trx_type' => 3,
        ],
        'ubl_m_waqas_jama' => [
            'label' => 'UBL وقاص',
            'side' => 'incoming',
            'sort' => 76,
            'type' => 'vendor_ledger',
            'vendor_id' => 285,
            'direction' => 'cr',
            'trx_type' => 3,
        ],
        'abdul_shakoor_exchange_jama' => [
            'label' => 'نقد رقم شہر دکان',
            'side' => 'incoming',
            'sort' => 12,
            'type' => 'vendor_ledger',
            'vendor_id' => 33,
            'direction' => 'cr',
            'trx_type' => 3,
        ],
        'sody_khareed' => [
            'label' => 'سودے خرید',
            'side' => 'outgoing',
            'sort' => 195,
            'type' => 'formula_sody_khareed',
        ],
    ],

    'product_lines' => [
        ['slug' => 'dawai', 'label' => 'دوائی', 'side' => 'incoming', 'sort' => 110, 'company_ids' => [35, 36], 'show_qty' => true, 'subtract_returns' => true, 'categorized' => true],
        ['slug' => 'beej', 'label' => 'بیج', 'side' => 'incoming', 'sort' => 111, 'company_ids' => [14, 60], 'show_qty' => true, 'subtract_returns' => true, 'categorized' => true],
        ['slug' => 'gandom', 'label' => 'گندم', 'side' => 'incoming', 'sort' => 112, 'company_ids' => [39], 'show_qty' => true, 'categorized' => true],
        ['slug' => 'kapas', 'label' => 'بنولہ', 'side' => 'incoming', 'sort' => 113, 'company_ids' => [40], 'show_qty' => true, 'categorized' => true],
        ['slug' => 'dhaan', 'label' => 'دھان', 'side' => 'incoming', 'sort' => 114, 'company_ids' => [41], 'show_qty' => true, 'categorized' => true],
        ['slug' => 'dap_25kg', 'label' => 'ڈی اے پی 25 کلو', 'side' => 'incoming', 'sort' => 115, 'company_ids' => [42], 'show_qty' => true, 'categorized' => true],
        ['slug' => 'dap', 'label' => 'ڈی اے پی', 'side' => 'incoming', 'sort' => 116, 'company_ids' => [4], 'show_qty' => true, 'subtract_returns' => true, 'categorized' => true],
        ['slug' => 'tsp', 'label' => 'ٹی ایس پی', 'side' => 'incoming', 'sort' => 117, 'company_ids' => [83], 'show_qty' => true, 'subtract_returns' => true, 'categorized' => true],
        ['slug' => 'urea', 'label' => 'یوریا', 'side' => 'incoming', 'sort' => 118, 'company_ids' => [3], 'show_qty' => true, 'subtract_returns' => true, 'categorized' => true],
        ['slug' => 'can', 'label' => 'گوارہ', 'side' => 'incoming', 'sort' => 119, 'company_ids' => [5], 'show_qty' => true, 'subtract_returns' => true, 'categorized' => true],
        ['slug' => 'np', 'label' => 'نائیڑوفاس', 'side' => 'incoming', 'sort' => 120, 'company_ids' => [6], 'show_qty' => true, 'subtract_returns' => true, 'categorized' => true],
        ['slug' => 'ssp', 'label' => 'ایس ایس پی', 'side' => 'incoming', 'sort' => 121, 'company_ids' => [7], 'show_qty' => true, 'categorized' => true],
        ['slug' => 'zarkhez', 'label' => 'زرخیز', 'side' => 'incoming', 'sort' => 122, 'company_ids' => [8], 'show_qty' => true, 'categorized' => true],
        ['slug' => 'sop', 'label' => 'ایس او پی', 'side' => 'incoming', 'sort' => 123, 'company_ids' => [9], 'show_qty' => true, 'categorized' => true],
        ['slug' => 'jimsam', 'label' => 'جپسم', 'side' => 'incoming', 'sort' => 124, 'company_ids' => [10], 'show_qty' => true, 'categorized' => true],
        ['slug' => 'sm_urea', 'label' => 'sm_urea', 'side' => 'incoming', 'sort' => 125, 'company_ids' => [11], 'show_qty' => true, 'categorized' => true],
        ['slug' => 'mop', 'label' => 'ایم او پی', 'side' => 'incoming', 'sort' => 126, 'company_ids' => [12], 'show_qty' => true, 'categorized' => true],
        ['slug' => 'mutafirq_sody', 'label' => 'متفرق سودے', 'side' => 'incoming', 'sort' => 14, 'type' => 'formula_mutafirq_sody'],
    ],

    'customer_lines' => [
        ['slug' => 'fazul_qadir_receive', 'label' => 'فضل القادر', 'side' => 'incoming', 'sort' => 40, 'customer_id' => 48, 'direction' => 'cr'],
        ['slug' => 'fazul_qadir_banam', 'label' => 'فضل القادر', 'side' => 'outgoing', 'sort' => 40, 'customer_id' => 48, 'direction' => 'dr'],
        ['slug' => 'shafiq_karyana_receive', 'label' => 'شفیق کریانہ', 'side' => 'incoming', 'sort' => 41, 'customer_id' => 49, 'direction' => 'cr'],
        ['slug' => 'shafiq_karyana_banam', 'label' => 'شفیق کریانہ', 'side' => 'outgoing', 'sort' => 41, 'customer_id' => 49, 'direction' => 'dr'],
        ['slug' => 'abdul_ghaffar_ghar_receive', 'label' => 'عبدالغفار گھر', 'side' => 'incoming', 'sort' => 42, 'customer_id' => 107, 'direction' => 'cr'],
        ['slug' => 'abdul_ghaffar_ghar_banam', 'label' => 'عبدالغفار گھر', 'side' => 'outgoing', 'sort' => 42, 'customer_id' => 107, 'direction' => 'dr'],
        ['slug' => 'ammar_abdullah_ghar_receive', 'label' => 'عمار عبداللہ گھر', 'side' => 'incoming', 'sort' => 43, 'customer_id' => 113, 'direction' => 'cr'],
        ['slug' => 'ammar_abdullah_ghar_banam', 'label' => 'عمار عبداللہ گھر', 'side' => 'outgoing', 'sort' => 43, 'customer_id' => 113, 'direction' => 'dr'],
        ['slug' => 'imdad_khata_receive', 'label' => 'امداد کھاتہ', 'side' => 'incoming', 'sort' => 44, 'customer_id' => 126, 'direction' => 'cr'],
        ['slug' => 'imdad_khata_banam', 'label' => 'امداد کھاتہ', 'side' => 'outgoing', 'sort' => 44, 'customer_id' => 126, 'direction' => 'dr'],
        ['slug' => 'imran_niazi_receive', 'label' => 'عمران نیازی', 'side' => 'incoming', 'sort' => 45, 'customer_id' => 145, 'direction' => 'cr'],
        ['slug' => 'imran_niazi_banam', 'label' => 'عمران نیازی', 'side' => 'outgoing', 'sort' => 45, 'customer_id' => 145, 'direction' => 'dr'],
        ['slug' => 'sir_murtaza_sahib_receive', 'label' => 'سر مرتضیٰ صاحب', 'side' => 'incoming', 'sort' => 46, 'customer_id' => 157, 'direction' => 'cr'],
        ['slug' => 'sir_murtaza_sahib_banam', 'label' => 'سر مرتضیٰ صاحب', 'side' => 'outgoing', 'sort' => 46, 'customer_id' => 157, 'direction' => 'dr'],
        ['slug' => 'master_khalid_faroq_shah_receive', 'label' => 'ماسٹر خالد فاروق شاہ', 'side' => 'incoming', 'sort' => 47, 'customer_id' => 242, 'direction' => 'cr'],
        ['slug' => 'master_khalid_faroq_shah_banam', 'label' => 'ماسٹر خالد فاروق شاہ', 'side' => 'outgoing', 'sort' => 47, 'customer_id' => 242, 'direction' => 'dr'],
        ['slug' => 'karaya_dokan_receive', 'label' => 'کرایہ دکان', 'side' => 'incoming', 'sort' => 48, 'customer_id' => 115, 'direction' => 'cr'],
        ['slug' => 'karaya_dokan_banam', 'label' => 'کرایہ دکان', 'side' => 'outgoing', 'sort' => 48, 'customer_id' => 115, 'direction' => 'dr'],
        ['slug' => 'salries_banam', 'label' => 'تنخواہ ملازمین', 'side' => 'outgoing', 'sort' => 49, 'customer_id' => 114, 'direction' => 'dr'],
    ],

    'vendor_lines' => [
        ['slug' => 'gawara_khata', 'label' => 'گوارا خرید کھاتہ', 'side' => 'outgoing', 'sort' => 30, 'vendor_id' => 346, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'np_khareed', 'label' => 'خرید NP', 'side' => 'outgoing', 'sort' => 31, 'vendor_id' => 294, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'petrol_khata', 'label' => 'پٹرول', 'side' => 'outgoing', 'sort' => 32, 'vendor_id' => 264, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'abdul_shakoor_exchange', 'label' => 'نقد رقم شہر دکان', 'side' => 'outgoing', 'sort' => 33, 'vendor_id' => 33, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'habib_bank_abdul_shakoor', 'label' => 'حبیب بینک عبدالشکور', 'side' => 'outgoing', 'sort' => 34, 'vendor_id' => 312, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'dawaj_khareed', 'label' => 'dawaj_khareed', 'side' => 'outgoing', 'sort' => 35, 'vendor_id' => 394, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'angro_fertilizer', 'label' => 'اینگرو کھاد', 'side' => 'outgoing', 'sort' => 36, 'vendor_id' => 9, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'fouji_fertilizer', 'label' => 'فوجی فرٹیلائزرز', 'side' => 'outgoing', 'sort' => 37, 'vendor_id' => 17, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'dap_khata', 'label' => 'ڈی اے پی کھاتہ', 'side' => 'outgoing', 'sort' => 38, 'vendor_id' => 289, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'angro_khata', 'label' => 'یوریا کھاتہ', 'side' => 'outgoing', 'sort' => 39, 'vendor_id' => 290, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'fatima_flink_ventilators', 'label' => 'fatima_flink_ventilators', 'side' => 'outgoing', 'sort' => 50, 'vendor_id' => 18, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'wilkan_center_cotton', 'label' => 'wilkan_center_cotton', 'side' => 'outgoing', 'sort' => 51, 'vendor_id' => 34, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'tcs_tcs_wadha', 'label' => 'tcs_tcs_wadha', 'side' => 'outgoing', 'sort' => 52, 'vendor_id' => 36, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'sami_sami', 'label' => 'sami_sami', 'side' => 'outgoing', 'sort' => 52, 'vendor_id' => 135, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'nmlf', 'label' => 'nmlf', 'side' => 'outgoing', 'sort' => 53, 'vendor_id' => 138, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'abl_ka', 'label' => 'ABL کوٹ ادو', 'side' => 'outgoing', 'sort' => 54, 'vendor_id' => 278, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'ubl_waqas', 'label' => 'UBL وقاص', 'side' => 'outgoing', 'sort' => 55, 'vendor_id' => 285, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'bank_al_habib_ka', 'label' => 'بینک الحبیب', 'side' => 'outgoing', 'sort' => 56, 'vendor_id' => 298, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'bop_card_loss', 'label' => 'bop_card_loss', 'side' => 'outgoing', 'sort' => 57, 'vendor_id' => 306, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'hbl_m_waqas', 'label' => 'HBL وقاص', 'side' => 'outgoing', 'sort' => 58, 'vendor_id' => 311, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'sarhad_punjab_cash', 'label' => 'sarhad_punjab_cash', 'side' => 'outgoing', 'sort' => 59, 'vendor_id' => 315, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'alfalah_bank_card', 'label' => 'alfalah_bank_card', 'side' => 'outgoing', 'sort' => 60, 'vendor_id' => 323, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'tameerat_khata', 'label' => 'تعمیرات کھاتہ', 'side' => 'outgoing', 'sort' => 61, 'vendor_id' => 340, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'baghban_chemical', 'label' => 'باغبان کیمیکلز', 'side' => 'outgoing', 'sort' => 62, 'vendor_id' => 343, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'prime_khata', 'label' => 'پرائم کھاتہ', 'side' => 'outgoing', 'sort' => 63, 'vendor_id' => 472, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'imported_pura_khata', 'label' => 'imported_pura_khata', 'side' => 'outgoing', 'sort' => 64, 'vendor_id' => 366, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'bop_bank', 'label' => 'BOP الیاس', 'side' => 'outgoing', 'sort' => 65, 'vendor_id' => 374, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'sonehri_bank', 'label' => 'سنہری بینک', 'side' => 'outgoing', 'sort' => 66, 'vendor_id' => 377, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'askari_bank', 'label' => 'askari_bank', 'side' => 'outgoing', 'sort' => 67, 'vendor_id' => 379, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'amanat_bank', 'label' => 'amanat_bank', 'side' => 'outgoing', 'sort' => 68, 'vendor_id' => 387, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'wilkan_chemicals', 'label' => 'ویلکان کیمیکلز', 'side' => 'outgoing', 'sort' => 70, 'vendor_id' => 20, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'swat_agro_chemicals', 'label' => 'سوات ایگرو کیمیکلز', 'side' => 'outgoing', 'sort' => 71, 'vendor_id' => 19, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'agro_lux', 'label' => 'ایگرو لکس', 'side' => 'outgoing', 'sort' => 72, 'vendor_id' => 21, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'kenzo_ag', 'label' => 'کینزو اے جی', 'side' => 'outgoing', 'sort' => 73, 'vendor_id' => 22, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'leader_ag', 'label' => 'لیڈر اے جی', 'side' => 'outgoing', 'sort' => 74, 'vendor_id' => 23, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'arsta', 'label' => 'arsta', 'side' => 'outgoing', 'sort' => 75, 'vendor_id' => 24, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'bayer', 'label' => 'Bayer', 'side' => 'outgoing', 'sort' => 76, 'vendor_id' => 25, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'fmc', 'label' => 'FMC', 'side' => 'outgoing', 'sort' => 77, 'vendor_id' => 26, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'agro_mark', 'label' => 'ایگرو مارک', 'side' => 'outgoing', 'sort' => 78, 'vendor_id' => 27, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'advance_agro_tech', 'label' => 'advance_agro_tech', 'side' => 'outgoing', 'sort' => 79, 'vendor_id' => 29, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'gandum_khareed_khata', 'label' => 'گندم خرید کھاتہ', 'side' => 'outgoing', 'sort' => 80, 'vendor_id' => 413, 'direction' => 'dr', 'in_vendor_total' => true],
        ['slug' => 'land_company', 'label' => 'مائی لینڈ کمپنی', 'side' => 'outgoing', 'sort' => 81, 'vendor_id' => 341, 'direction' => 'dr', 'in_vendor_total' => true],
    ],

    'totals' => [
        'incoming_footer' => [
            ['slug' => 'ttl_in', 'label' => 'کل آمد', 'highlight' => true],
        ],
        'outgoing_footer' => [
            ['slug' => 'ttl_out', 'label' => 'کل نکاس', 'highlight' => true],
            ['slug' => 'total_meezan', 'label' => 'کل میزان', 'highlight' => true, 'formula' => 'ttl_in_minus_ttl_out'],
        ],
    ],
];
